version: "3.4"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "firstapp"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  firstapp-db:
    image: firstapp-db:latest
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/firstapp
      - DB_SCHEMA=fa
      - DB_LOGIN=postgres
      - DB_PASSWORD=postgres
  firstapp:
    image: firstapp:latest
    ports:
      - "8080:8080"
    depends_on:
      firstapp-db:
        condition: service_completed_successfully
    env_file: ./firstapp/application.env
